spring:
  cloud:
    config:
      name: discovery-server
      profile: dev
      label: latest

  config:
    import:
    - configserver:http://config-server:9000

eureka:
  client:
    registerWithEureka: false   
    fetchRegistry: false